# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Purchasely-iOS-DemoFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Purchasely-iOS-DemoFirebase
	pod 'Firebase/Auth'
#	pod 'Firebase/Firestore'
	pod 'FirebaseFirestoreSwift', '8.2.0-beta'
	pod 'Purchasely'

end
